image: docker:latest
variables:
  DOCKER_DRIVER: overlay
  CRYPTOGRAPHY_DONT_BUILD_RUST: 1
services:
  - docker:dind

before_script:
    - docker info
    - apk update
    - apk upgrade
    - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install --upgrade pip
    - echo "cryptography==3.3.2" > /tmp/requirements.txt
    - pip3 install -U docker-compose -r /tmp/requirements.txt
    - rm /tmp/requirements.txt

stages:
  - build
  - deploy-kubernetes

build-app:
  stage: build
  variables:
    ENVIRONMENT: 'staging'
  script:
    - touch .env
    - echo "ENVIRONMENT=${ENVIRONMENT}" > .env
    - echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
    - echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
    - echo "HOST_NAME=${HOST_NAME}" >> .env
    - echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
    - echo "DATABASE_URL=${DATABASE_URL}" >> .env
    - docker-compose up -d
  only:
    - branches
  
deploy_review:
  stage: deploy-kubernetes
  script:
    - echo "Deploy a review app 🚀"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$APPS_DOMAIN
    - branches
  only:
    - branches